package englishtutor;


import java.util.Properties;

//import javax.mail.Message;
//import javax.mail.MessagingException;
//import javax.mail.PasswordAuthentication;
//import javax.mail.Session;
//import javax.mail.Transport;
//import javax.mail.internet.InternetAddress;
//import javax.mail.internet.MimeMessage;
//import jakarta.mail;
import jakarta.mail.Session;
import jakarta.mail.*;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;


//import jakarta.servlet.RequestDispatcher;


//import java.util.Properties;

public class SendEmail {
	
	
	public SendEmail() {
        super();
        // TODO Auto-generated constructor stub
    }
	
	public void send(String email,String emailcontent,String emailsubject) {
	// Recipient's email ID needs to be mentioned.
    String to = email;

    // Sender's email ID needs to be mentioned
    String from = "jsu01854@gmail.com";

    // Assuming you are sending email from through gmails smtp
    String host = "smtp.gmail.com";
    //final String username = "jsu01854";//username generated by Mailtrap
    //final String username = "Jan-Hon";//username generated by Mailtrap
    final String username = "jsu01854@gmail.com";//username generated by Mailtrap
    //final String username = "janhonsu@gmail.com";//username generated by Mailtrap
    //final String password = "01854@Jsu";//password generated by Mailtrap
    //final String password = "fnju zhgh fqil uuls";//password generated by Mailtrap
    final String password = "yozl rcvn rqry kzpq";//password generated by Mailtrap

    // Get system properties
    Properties props = new Properties();
    props.put("mail.smtp.auth", "true");
    props.put("mail.smtp.starttls.enable", "true");
    props.put("mail.smtp.host", "smtp.gmail.com");
    props.put("mail.smtp.port", "587");
    //props.put("mail.smtp.username", "jsu01854@gmail.com");
    //props.put("mail.smtp.password", "fnju zhgh fqil uuls"); 
    System.out.println("Sent 1");
    // Get the Session object.// and pass username and password
    //Session session = Session.getInstance(props, null)
    /*
    Session session = Session.getInstance(props, new jakarta.mail.Authenticator(){
        protected jakarta.mail.PasswordAuthentication getPasswordAuthentication() {
            return new jakarta.mail.PasswordAuthentication(from, "01854@Jsu");
        }
    });
*/
    Session session = Session.getInstance(props, new Authenticator(){
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(username, password);
        }
    });
    System.out.println("Sent 2");

    // Used to debug SMTP issues
    session.setDebug(true);

    try {
    	
    	Message message = new MimeMessage(session);
        System.out.println("Sent 3");
    	message.setFrom(new InternetAddress(from));
        System.out.println("Sent 4");
    	message.setRecipients(Message.RecipientType.TO,
    	        InternetAddress.parse(to));
        System.out.println("Sent 5");
    	//message.setSubject("Your English Tutor Temparory password");

    	message.setSubject(emailsubject);

        System.out.println("Sent 6");
    	message.setText(emailcontent);
    	
    	Transport.send(message);
    	System.out.println("Mail successfully sent!");
    	
        
    } catch (MessagingException mex) {
    	 throw new RuntimeException(mex);
    }

}	
	
}